version: '3.4'

services:
  api:
    image: "programminglaboratory.pracowaniaprogramowania.api:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5151:80"
    restart: always
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Mb7!W7V*MXtE[4Z9"
      ACCEPT_EULA: "Y"